version: "2"
services:
  organizr:
    image: lsiocommunity/organizr
    ports:
      - "80/tcp:80/tcp" # Web UI
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/organizr:/config
    env_file:
      - var.env
  deluge:
    image: linuxserver/deluge
    ports:
      - "8112/tcp:8112/tcp" # Web UI
      - "62958/tcp:62958/tcp" # Torrent
      - "62958/udp:62958/udp" # Torrent
      - "58846/tcp:58846/tcp" # Daemon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/deluge:/config
      - /mnt/storage/media-server/download:/downloads
    env_file:
      - var.env
  sabnzbd:
    image: linuxserver/sabnzbd
    ports:
      - "8080/tcp:8080/tcp" # Web UI http
      - "9090/tcp:9090/tcp" # Web UI https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sabnzb:/config
      - /mnt/storage/media-server/download:/downloads
    env_file:
      - var.env
  sonarr:
    image: linuxserver/sonarr
    ports:
      - "8989/tcp:8989/tcp" # Web UI http
      - "9898/tcp:9898/tcp" # Web UI https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sonarr:/config
      - /mnt/storage/media-server/download:/downloads
      - /mnt/storage/media-server/library/tvshows:/tv
    env_file:
      - var.env
  radarr:
    image: linuxserver/radarr
    ports:
      - "7878/tcp:7878/tcp" # Web UI http
      - "8787/tcp:8787/tcp" # Web UI https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config
      - /mnt/storage/media-server/download:/downloads
      - /mnt/storage/media-server/library/movies:/movies
    env_file:
      - var.env
  lidarr:
    image: linuxserver/lidarr
    ports:
      - "8686/tcp:8686/tcp" # Web UI http
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/lidarr:/config
      - /mnt/storage/media-server/download:/downloads
      - /mnt/storage/media-server/library/music:/music
    env_file:
      - var.env
  lazylibrarian:
    # Web UI at http://localhost:5299
    image: linuxserver/lazylibrarian
    ports:
      - "5299:5299" # Web UI
    volumes:
      - ./config/lazylibrarian:/config
      - /mnt/storage/media-server/download:/downloads
      - /mnt/storage/media-server/library/books:/books
    env_file:
      - var.env
  plex:
    image: linuxserver/plex
    # Plex uses UPNP to open connections dynamically on request. These
    # connections use whichever port the UPNP server (usually the router) tells
    # it to. There is no way to know what these ports will be, nor any way to
    # allow Docker to open them dynamically. Therefore, host mode networking is
    # required.
    # Web UI at http://localhost:32400/web
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/plex:/config
      - /mnt/storage/media-server/library/tvshows:/data/tvshows
      - /mnt/storage/media-server/library/movies:/data/movies
      - /mnt/storage/media-server/library/music:/data/music
      - /tmp/transcode:/transcode
    env_file:
      - var.env
    environment:
      # - VERSION=latest # Use this version if you do not have a plexpass
      - VERSION=public # Use this version if you do have a plexpass
